spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creator_directory?options=-c%20TimeZone=UTC
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080